apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: postech
type: Opaque
# Todos os valores devem ser codificados em base64.
# Para gerar: echo -n "valor" | base64
# Para o APP_KEY, use: php artisan key:generate --show | base64
# Para o JWT_SECRET, use: php artisan jwt:secret --show | base64
stringData:
  APP_KEY: "base64:BBZgVlgdt2i/fm54/cAtNhwJHwuMXMj3rZ8PdR9D+os="
  DB_PASSWORD: "123123"
  JWT_SECRET: "LXdsVa6dYsscAXLS9zRJ2eDL1gPbFBfPHwAt94Eq6LsWhncHjzOqloKIOEDSXMaU"
  MAIL_USERNAME: "evdwsoat15@gmail.com"
  MAIL_PASSWORD: "evdwsoat15123"
