apiVersion: v1
kind: Service
metadata:
  name: postech-app
  namespace: postech
  labels:
    app: postech-app
spec:
  # Use LoadBalancer em ambientes cloud (EKS, GKE, AKS).
  # Use NodePort para Minikube/Kind local.
  type: LoadBalancer
  selector:
    app: postech-app
  ports:
    - name: http
      port: 8080
      targetPort: 8000
      protocol: TCP
