apiVersion: v1
kind: Service
metadata:
  name: swagger-ui
  namespace: postech
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-09b4b21669d06b2fd"
  labels:
    app: swagger-ui
spec:
  type: LoadBalancer
  selector:
    app: swagger-ui
  ports:
    - name: http
      port: 8082
      targetPort: 8080
      protocol: TCP
