apiVersion: v1
kind: Service
metadata:
  name: swagger-ui
  namespace: postech
  labels:
    app: swagger-ui
spec:
  type: LoadBalancer
  selector:
    app: swagger-ui
  ports:
    - name: http
      port: 8082
      targetPort: 8080
      protocol: TCP
