apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  namespace: postech
  labels:
    app: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: SWAGGER_JSON
              value: /app/openapi.yaml
          volumeMounts:
            - name: openapi-spec
              mountPath: /app/openapi.yaml
              subPath: openapi.yaml
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
      volumes:
        - name: openapi-spec
          configMap:
            name: openapi-spec
---
# Para criar o ConfigMap com o arquivo openapi.yaml, execute:
# kubectl create configmap openapi-spec --from-file=openapi.yaml -n postech
